### ISSUE TITLE
i am having a lots of confusion need help regarding node 4.8.4 directory

### ISSUE THREAD

**Issue by rizwan92** [mongoclient/mongoclient-electron#3]
```Copy Node (4.8.4) to bin folder
Copy Mongod (>= 3.2.6) to bin folder
Run npm install on scaffold directory```

i dont get this part where is this folder and where should i paste it and there is no package.json file 
 where i have to fire npm install in app folder

**Comment by rsercano** [comment]
Scaffold directory is this repo, so you need to run `npm install` on this directory as described in the steps.

**Comment by rizwan92** [comment]
at first i copied all the  directory inside .meteor\build\bundle\programs\server\npm\node_modules to my scaffold directory/program/server/npm/node_modules

but i am having problem at second stage where i have to copy node4.8.5 directory to  my scaffold directory/program/server/npm/node_modules

i  am not able to find this node4.8.4 directory inside .meteor\build\bundle\programs\server\npm\node_modules 

please help me i am probably gonna loose my job

**Comment by rizwan92** [comment]
ohhhh now i get it nosqlclient-electron means this repo is the scaffold directory,
first i have to clone it then put my meteor application bundle inside app folder then i need to run  npm install rigth ?

**Comment by rsercano** [comment]
yeah, that's true :)

**Comment by rizwan92** [comment]
last two question after i putting  my meteor bundle inside app folder of this repo

1. where is the node 4.8.4 and mongod which i need to copy into bin directory ?

2. where is the bin directory ?
bin of this repo node_modules or my meteor bundle node_modules?

thanks in advance

**Comment by rsercano** [comment]
executables should be in bin directory as far as I remember, check the README.md and bin is already located in the repo,
